### PR TITLE
Bootstrapping

### PR DESCRIPTION
**Pull request by dwhswenson**
It’s a godawful ugly algorithm, but it works, and I’ve implemented two other features we had previously discussed:

1. Conditional (if-then-else) movers
2. Replica ID Filters (as movers)

Both are done kinda halfway. In particular, we will want to clean up the filters a bit (it doesn’t even include move path support.) But I wanted to get the barely-working thing in.

No tests on either of those, nor on the addition of the `sample.intermediate` feature.

We still fail the "lambda not JSON serializable" bug in the toy storage. We also fail that in master, which sucks. That should be probably be the first priority to fix.

### CODE REVIEW

**Comment by dwhswenson** [comment]
Looks like Travis tests don't happen automatically here: my local tests passed `nosetests` and `alanine.ipynb`. Didn't test anything else. It will fail `toy_dynamics_tis.ipynb`, but only because choderalab/master fails that too (as mentioned above).

**Comment by jhprinz** [comment]
I will look into the not serializable. I think this does not happen on my machine, which is weird.

**Comment by jhprinz** [comment]
Just went through the code and the changes I suggest are even much smaller than I thought.

I think we should remove the intermediate property from all Movers, except the SampleMovePath. This introduces a source of error and requires always to think about this even if moves have nothing to do with creating intermediate samples.

If I read your code correctly and understand the problem, then what we want is that from a sublist of all the samples (which are generated by the MovePath), so why not use a MovePath, that filters out all samples that we do not want. If this is applied at the right point then we should get the desired list of samples and can apply it to the SampleSet.

Let me give an example for the HopMover, which is either
1. shoot and reject -> no sample to apply
2. shoot, accept, try hop, reject -> only apply the shoot sample
3. shoot, accept, try hop, accept -> only apply the shoot sample with new RepID

So let's just write

```
def EnsembleHopper(PathMover):

    def move(self, globalstate):
        return KeepLastSampleMovePath(
            PartialAcceptanceSequentialMover(
                [shooter, hopper]
            ).move(globalstate)
        )
```
this uses the known Movers to construct the move path as we do right now and then
add a *directive* to only keep the last sample of the ones generated.

and implement

```
class KeepLastSampleMover(MovePath):
    def __init__(self, movepath):
        super(SequentialMovePath, self).__init__()
        self.movepath = movepath

    def _get_samples(self):
        samples = self.movepath.samples
        if len(samples) > 1:
            samples = [samples[-1]]

        return samples
```

That's it. Or course keep all the rest of your code. I really like the Filter idea. Is is okay, if I just merge and add this and get it to work?

**Comment by dwhswenson** [comment]
I don't like the idea of

**Comment by dwhswenson** [comment]
(Sorry, this is from my phone -- give me a moment to write the whole thing)

**Comment by dwhswenson** [comment]
I don't like the idea of creating extra classes if not necessary. The hop class you have is not a reasonable thing to expect anyone to reuse. You also still don't have anything to handle replica ID changing. If you're going to do that, then we're not really 

I also think every move should have one and only one return type. What you're suggesting says: "the return type is A, unless the sample is supposed to be an intermediate, in which case the return type is B". That means every PathMover needs an if statement in their return.

So either we break one return type per mover or we have to create many more classes. This does not seem simpler to me.

A KeepLast lSample move path is reasonable, but I would think it makes more sense to do that as a mover that wraps other movers.

Anyway, brief bc I'm running errands.

**Comment by jhprinz** [comment]
Damn, I just deleted my post... :)

Totally agree with you.
1. No if statements, that was the point I tried to make against using intermediate which requires little changes in all movers
2. Every move should have one return type: a MovePath! And a MovePath can create the necessary list of samples, so there is a MovePath than can reduce the inner samples to the last one.
3. Since we might need the reduction step anyway we can implement it. Usually a user does not see it and in the movepath output it will only state that of all the inner samples only one is really used (the last one)
4. Right my Hopper is not useful and I meant that the BootstrapPromotionMove need to add the KeepLastSample to make it very simple. We could name the old hopper `CloneInNewEnsembleMover`
5. Error in the above example: The second class is a MovePath, not a mover, sorry!!!
```
class KeepLastSampleMovePath(MovePath):
    def __init__(self, movepath):
        super(SequentialMovePath, self).__init__()
        self.movepath = movepath

    def _get_samples(self):
        samples = self.movepath.samples
        if len(samples) > 1:
            samples = [samples[-1]]

        return samples
```
5. Sure a Mover that does the same thing would be easy. It looks like

```
class RestrictToLastSampleMover(PathMover):
    def __init__(self, inner_mover):
        self.inner_mover = inner_mover

    def move(self, globalstate):
        movepath = self.inner_mover(global state)
        return KeepLastSampleMovePath(movepath)
```

and then the BootstrapPromotionMover looks like

```
class BPM(PathMover)

    def move(self, globalstate):
        mover = RestrictToLastSampleMover(
            PartialAcceptanceSequentialMover(
                [shooting_mover, hopping_mover]
            )
        )
```

It is just that my feeling is to put the change of the samplelist in the authority of the MovePath and not the Mover, thats all. No other changes are required in any other class!

**Comment by jhprinz** [comment]
I will merge this, branch it and propose a few changes. That might it easiert to explain the difference

**Pull request merged**
