### PR TITLE
[WIP] Add hidden MovePath capabilities

### PR DESCRIPTION
**Pull request by jhprinz**
This adds the proposed way to use open and closed movepaths. Works nicely with storage.

All it does is that

`movepath.closed` replaces the MovePath by a CollapsedMovePath object and `movepath.opened` returns the old object. If you store a closed object then the loaded one will not allow to be opened. For example this way
the MinusMover only stores 2 samples now. And it can be loaded in the usual manner.

If you have access to a movepath that has been created by a MinusMove and is not loaded you can expand it back using `movepath.opened`

#### Example
```
print production_sampleset[0].movepath
                RandomChoice :
                 +- MinusMover [collapsed] : 2 samples [<Sample @ 0x10d9a1fd0>, <Sample @ 0x10d9a1e90>]
```

### CODE REVIEW

**Comment by jhprinz** [comment]
Sorry, had the wrong base branch

**Comment by dwhswenson** [comment]
It is unclear to me how this would allow you to specify to only mark one of the two samples generated by a given move.

**Comment by dwhswenson** [comment]
(Example to clarify previous: repex part of minus moves creates two samples: one is virtual, one is not. How does this approach allow that?)

**Comment by jhprinz** [comment]
Actually, right now you cannot specify exactly which samples you want to keep and which ones you do not. Example from the minus move you used before:

5 Samples are generated and usually returned. Three of these do not matter since they will be replaced by later samples. Thus only two matter (that are the ones which were not marked with a star). The `.closed` property just returns a kind of SampleMovePath that only contains these two samples.
I thought this was the problem. Of course, if you would like to exactly to specify which if these 5 samples you would like to keep, I can do that, too very easily.

It is then in fact (almost) equivalent to your initial idea, only that we do not apply the reduction to the Pathmover directly, but to the MovePath afterwards, but the result is similar. Only store selected samples.
In both cases you need to know exactly, what the underlying mover is doing and in which order which samples are generated to pick out the ones you want.

My naive approach just picks the smallest possible (but still correct) reduced step. I will just add a function that allows to pick specific samples as they come out to show what I mean. This works like this:

```
collapsed_movepath = movepath.closed # fully collapsed
partial_movepath = movepath.reduced([-1]) # returns only the last sample (and others if these are necessary to keep the move correct!
```

The main reason I did it this way was since it seemed easier to implement storage with what we had.
And it also allows to ensure that no relevant samples are forgotten. You will always get the correct sampleset, whatever you decide to keep since the `.reduce()` function takes care of this ! Otherwise you might loose some relevant samples and end up with other sample_sets than what you wanted.
Does that make sense?

**Comment by jhprinz** [comment]
Sorry, I think I forgot something, because the above function do NOT remove samples that are essential to the sample_set they only reduce the view. If you want to really remove samples you can do this by using a Filter, like your FilterByReplicaID or my new FilterSamplesMover, that allows to select specific samples.
```
bootstrapmover = FilterSampleMover(
    PartialAcceptanceSequentialMover(
        [shooter, hopper, replica_id_swap]
    ), -1
)
```

This is actually just what you had before with intermediate (and so the circle closes)

Sorry for all the confusion :)

**Comment by dwhswenson** [comment]
Yeah, let's go ahead and merge all of this in now. But I think we need to plan to revisit the separation of roles in `SampleSet`, `PathMover`, and `MovePath` before we can really write all of that up. But what we have here works, and we need to get working on some of analysis-related stuff. So I think we can wait for a little while before we clean up the mess we've made in this part.

**Comment by jhprinz** [comment]
I think you are right. Although what we have is already pretty cool, whatever it will be. I wanted to add some last thing and put back the option for pathmover to make them selectable to samples, like you had with intermediate in the first place. The only difference is again that we select samples after they are returned. Then I would merge it (if you agree) and go from there reducing to what we effectively want.

It seems it has kind of grown too powerful and flexible and become somehow confusing to use.

**Comment by dwhswenson** [comment]
Yep, exactly my thoughts on all points. As I mentioned, I think the key is that we need to sit down and figure out exactly what the roles of those three classes are, because now there's too much overlap. That will probably take some time on Skype to do, so let me know when you have the time to do that!

**Comment by jhprinz** [comment]
Great. Let's maybe sort this out next week, when I am back? Then we are on the same time and it should be easier.

Just added a decorator to enable this feature like
mover = MinusMover(..., keep_samples = [2,4])

This will just add a FilterSamplesMovePath that only keeps sample at index 2,4 from all the ones returned. I will not use it, but leave it in the code.

Will check that travis builds and then merge and send you the storage query hopefully still today.
Was good talking to you!

**Comment by jhprinz** [comment]
Tests passed. Will merge...

**Comment by jhprinz** [comment]
Merged!

**Pull request merged**
